on: push
name: Workflow
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
    - name: Install
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: yarn install
    - name: Build
      run: yarn build
    - name: Test
      run: yarn test
  publish:
    name: Publish
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
    - name: Install
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: yarn install
    - name: Build
      run: yarn build
    - name: Setup git
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
    - name: Publish
      run: yarn lerna:release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}